### PR TITLE
Introduce Hoa\Router\Http\Dav router

### PR DESCRIPTION
**Pull request by Hywan**
Since the DAV family (WebDAV, CalDAV and CardDAV) is an extension to HTTP, the `Hoa\Router\Http\Dav` class simply extends `Hoa\Router\Http` and defines new methods:
  * PROPFIND,
  * PROPPATCH,
  * MKCOL,
  * COPY,
  * MOVE,
  * LOCK,
  * UNLOCK.

The `Hoa\Router\Http` class moved to `Hoa\Router\Http\Http`. We ensure BC by declaring `Hoa\Router\Http\Http` as a flex entity. We do not have enought tests to validate this PR. Help is welcomed :-).

Thoughts?

### CODE REVIEW

**Comment by evert** [comment]
HTTP applications really should not restrict the methods used, and neither should Hoa\Router. This list is currently incomplete =)

**Comment by evert** [comment]
So you should either copy the official IANA method list, or (better yet) don't base http methods on a hardcoded list.

http://www.iana.org/assignments/http-methods

**Comment by Hywan** [comment]
We use a list for security reasons. Thanks for the official list!

**Comment by Hywan** [comment]
List updated. /cc @hoaproject/hoackers for a review :-).

**Pull request merged**
