### PR TITLE
Fix typographical error(s)

### PR DESCRIPTION
**Pull request by orthographic-pedant**
@hoaproject, I've corrected a typographical error in the documentation of the [Router](https://github.com/hoaproject/Router) project. Specifically, I've changed confortable to comfortable. You should be able to merge this pull request automatically. However, if this was intentional or if you enjoy living in linguistic squalor, please let me know and [create an issue](https://github.com/thoppe/orthographic-pedant/issues/new) on my home repository.

### CODE REVIEW

**Comment by Hywan** [comment]
Thanks little bot!

**Comment by orthographic-pedant** [comment]
You are welcome little human!

**Comment by Hywan** [comment]
@orthographic-pedant Who's your creator?

**Comment by thoppe** [comment]
That would be me. I'm glad you found some use out of this. As of 5 minutes ago, GitHub just killed the project. The @orthographic-pedant is dead. Long live pedantry!

**Pull request merged**
